lecture:
  - docs/lecture/**/*

lab:
  - docs/lab/**/*

project:
  - docs/project/**/*
  - docs/project.md

workflow:
  - .github/**/*

website:
  - src/**/*
  - static/**/*
  - '*.js'
  - '*.json'
  - '*.ts'
